export const adminKeys = {
  all: ['admin'] as const,
  stats: () => [...adminKeys.all, 'stats'] as const,
  locations: (type: 'lost' | 'found') => [...adminKeys.all, 'locations', type] as const,
  hourly: (type: 'lost' | 'found') => [...adminKeys.all, 'hourly', type] as const,
  weekly: () => [...adminKeys.all, 'weekly'] as const,
  monthly: () => [...adminKeys.all, 'monthly'] as const,
  userActivity: (type: 'lost' | 'found' | 'comment') =>
    [...adminKeys.all, 'userActivity', type] as const,
  commentTrend: () => [...adminKeys.all, 'commentTrend'] as const,
  reportHandling: () => [...adminKeys.all, 'reportHandling'] as const,
  funnel: () => [...adminKeys.all, 'funnel'] as const,
  wordcloud: () => [...adminKeys.all, 'wordcloud'] as const,
  recentLost: () => [...adminKeys.all, 'recent-lost'] as const,
  recentFound: () => [...adminKeys.all, 'recent-found'] as const,
  users: () => [...adminKeys.all, 'users'] as const,
  usersInfinite: () => [...adminKeys.all, 'users-infinite'] as const,
  lost: () => [...adminKeys.all, 'lost'] as const,
  lostInfinite: () => [...adminKeys.all, 'lost-infinite'] as const,
  found: () => [...adminKeys.all, 'found'] as const,
  foundInfinite: () => [...adminKeys.all, 'found-infinite'] as const,
  categories: () => [...adminKeys.all, 'categories'] as const,
  announcements: () => [...adminKeys.all, 'announcements'] as const,
  announcementsInfinite: () => [...adminKeys.all, 'announcements-infinite'] as const,
  knowledgeDocuments: () => [...adminKeys.all, 'knowledge-documents'] as const,
};
